// Package compose turns a parsed owlab.yaml into a Docker Compose file
// and the build context it refers to.
//
// Compose is an implementation detail: nothing outside this package should
// know the file exists. It is written into .owlab/ next to the project so
// that a developer debugging a strange container can read exactly what was
// asked for, but it is generated on every run and must never be edited.
package compose

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	owlab "github.com/VizzleTF/owlab"
	"github.com/VizzleTF/owlab/internal/config"
	"github.com/VizzleTF/owlab/internal/engine"
)

// WorkDirName is the per-project scratch directory owlab writes into.
const WorkDirName = ".owlab"

// File is the generated compose document.
type File struct {
	Name     string             `yaml:"name"`
	Services map[string]Service `yaml:"services"`
	Networks map[string]Network `yaml:"networks"`
}

// Service is one router.
type Service struct {
	Build           *Build            `yaml:"build,omitempty"`
	Image           string            `yaml:"image,omitempty"`
	Platform        string            `yaml:"platform,omitempty"`
	ContainerName   string            `yaml:"container_name"`
	Hostname        string            `yaml:"hostname"`
	CapAdd          []string          `yaml:"cap_add,omitempty"`
	Privileged      bool              `yaml:"privileged,omitempty"`
	Ports           []string          `yaml:"ports,omitempty"`
	Environment     map[string]string `yaml:"environment,omitempty"`
	Volumes         []string          `yaml:"volumes,omitempty"`
	Restart         string            `yaml:"restart,omitempty"`
	StopGracePeriod string            `yaml:"stop_grace_period,omitempty"`
	TTY             bool              `yaml:"tty,omitempty"`
	Init            *bool             `yaml:"init,omitempty"`
	Labels          map[string]string `yaml:"labels,omitempty"`
}

// Build is the build stanza for one router.
//
// There is deliberately no platform here. The compose spec has build.platforms
// (a list, for multi-platform builds) and rejects a scalar build.platform; the
// service-level platform below already selects what to build and what to run,
// which is what a single-arch dev router wants.
type Build struct {
	Context    string            `yaml:"context"`
	Dockerfile string            `yaml:"dockerfile"`
	Args       map[string]string `yaml:"args,omitempty"`
}

// Network is the single user-defined bridge every router joins.
type Network struct {
	Name   string `yaml:"name"`
	Driver string `yaml:"driver"`
}

// Project bundles everything owlab needs to drive compose for one config.
type Project struct {
	Name        string
	WorkDir     string
	ComposePath string
	ContextDir  string
	Config      *config.Config
}

// Prepare writes the build context and the compose file, and returns where
// they landed.
func Prepare(cfg *config.Config, eng engine.Info) (*Project, error) {
	work := filepath.Join(cfg.Dir, WorkDirName)
	ctxDir := filepath.Join(work, "context")
	if err := os.MkdirAll(ctxDir, 0o755); err != nil {
		return nil, err
	}
	if err := writeGitignore(work); err != nil {
		return nil, err
	}
	if err := extractContext(ctxDir); err != nil {
		return nil, fmt.Errorf("writing build context: %w", err)
	}

	name := ProjectName(cfg.Project.Name)
	doc := File{
		Name:     name,
		Services: map[string]Service{},
		Networks: map[string]Network{
			"default": {Name: name, Driver: "bridge"},
		},
	}
	for i := range cfg.Routers {
		r := &cfg.Routers[i]
		if r.Fidelity == config.VM {
			// The VM tier does not run under compose at all — it spawns QEMU
			// natively on the host, because Docker Desktop grants containers
			// no /dev/kvm on macOS or Windows 10.
			continue
		}
		svc, err := service(cfg, r, eng, name, ctxDir)
		if err != nil {
			return nil, fmt.Errorf("router %q: %w", r.ID, err)
		}
		doc.Services[r.ID] = svc
	}

	out, err := yaml.Marshal(doc)
	if err != nil {
		return nil, err
	}
	header := "# Generated by owlab from " + config.FileName + ". Do not edit — it is rewritten on every run.\n"
	composePath := filepath.Join(work, "compose.yaml")
	if err := os.WriteFile(composePath, append([]byte(header), out...), 0o644); err != nil {
		return nil, err
	}

	return &Project{
		Name:        name,
		WorkDir:     work,
		ComposePath: composePath,
		ContextDir:  ctxDir,
		Config:      cfg,
	}, nil
}

func service(cfg *config.Config, r *config.Router, eng engine.Info, project, ctxDir string) (Service, error) {
	args := map[string]string{
		"PKG_MANAGER":   string(r.PackageManager()),
		"PACKAGES":      strings.Join(r.Packages, " "),
		"FIXTURES":      strings.Join(r.Fixtures, " "),
		"ROOT_PASSWORD": rootPassword(),
	}
	if base := r.BaseImage(); base != "" {
		args["BASE_STAGE"] = "upstream"
		args["BASE_IMAGE"] = base
	} else {
		args["BASE_STAGE"] = "tarball"
		args["ROOTFS_URL"] = r.RootfsTarballURL()
	}

	svc := Service{
		Build: &Build{
			Context:    ctxDir,
			Dockerfile: "Dockerfile",
			Args:       args,
		},
		Image:         fmt.Sprintf("%s-%s:latest", project, r.ID),
		Platform:      r.Platform(),
		ContainerName: fmt.Sprintf("%s-%s", project, r.ID),
		Hostname:      r.Hostname,
		// NET_ADMIN and NET_RAW rather than privileged: netifd has to bring
		// interfaces up and add addresses, and fw4 has to load an nftables
		// ruleset, but neither needs the rest of what privileged grants.
		CapAdd: []string{"NET_ADMIN", "NET_RAW"},
		// Host ports are the ONLY portable way in. A bridge subnet is
		// routable from the host on native Linux and inside WSL2, but not on
		// Docker Desktop for Mac or Windows — so nothing in owlab may
		// address a router by its bridge IP.
		Ports: []string{
			fmt.Sprintf("%d:80", r.Ports.HTTP),
			fmt.Sprintf("%d:22", r.Ports.SSH),
		},
		Environment: map[string]string{
			"OWLAB_DNS": dns(),
		},
		Restart:         "unless-stopped",
		StopGracePeriod: "5s",
		// procd writes its startup messages to /dev/console; without a tty
		// they go nowhere and `logs` is empty.
		TTY: true,
		// procd IS the init system here. Docker's own init would take PID 1
		// and everything that reads board data over ubus would come back
		// empty — which is what makes LuCI crash rather than degrade.
		Init: boolPtr(false),
		Labels: map[string]string{
			"org.owlab.project":  cfg.Project.Name,
			"org.owlab.router":   r.ID,
			"org.owlab.distro":   string(r.Distro),
			"org.owlab.release":  r.Release,
			"org.owlab.arch":     r.Arch,
			"org.owlab.fidelity": string(r.Fidelity),
		},
	}

	if key := publicKeyPath(); key != "" {
		// Staged at a read-only path and copied into place by the entrypoint,
		// because on native Linux a bind mount keeps the host's uid and
		// dropbear silently refuses an authorized_keys it does not see as
		// root's.
		svc.Volumes = append(svc.Volumes, key+":/etc/owlab/authorized_keys.host:ro")
	}
	return svc, nil
}

// extractContext writes the embedded build context to disk.
//
// Docker needs a real directory: BuildKit can take a context over stdin, but
// only as a tar stream, and that path loses the file modes the overlay
// depends on.
func extractContext(dir string) error {
	src := owlab.BuildContext()
	// Remove first, so a file dropped from a newer owlab does not linger in a
	// project directory that an older one wrote.
	if err := os.RemoveAll(dir); err != nil {
		return err
	}
	return fs.WalkDir(src, ".", func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		target := filepath.Join(dir, filepath.FromSlash(p))
		if d.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		b, err := fs.ReadFile(src, p)
		if err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		mode := fs.FileMode(0o644)
		if strings.HasSuffix(p, ".sh") || strings.Contains(p, "uci-defaults/") {
			mode = 0o755
		}
		return os.WriteFile(target, b, mode)
	})
}

func writeGitignore(work string) error {
	// Everything in here is generated. Writing the ignore file ourselves
	// keeps it out of the developer's repository without asking them to
	// remember a line in .gitignore.
	return os.WriteFile(filepath.Join(work, ".gitignore"), []byte("*\n"), 0o644)
}

// ProjectName is the compose project name, and the prefix of every container
// and network name.
func ProjectName(s string) string {
	s = strings.ToLower(s)
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == '-' || r == '_':
			b.WriteRune('-')
		}
	}
	out := strings.Trim(b.String(), "-")
	if out == "" {
		out = "project"
	}
	return "owlab-" + out
}

// publicKeyPath finds an ssh public key to install, preferring the modern
// default. Returns "" when there is none, in which case password auth is the
// way in.
func publicKeyPath() string {
	if p := os.Getenv("OWLAB_PUBKEY"); p != "" {
		return p
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	for _, name := range []string{"id_ed25519.pub", "id_ecdsa.pub", "id_rsa.pub"} {
		p := filepath.Join(home, ".ssh", name)
		if st, err := os.Stat(p); err == nil && !st.IsDir() {
			return p
		}
	}
	return ""
}

func rootPassword() string {
	if p := os.Getenv("OWLAB_ROOT_PASSWORD"); p != "" {
		return p
	}
	return "owlab"
}

func dns() string {
	if d := os.Getenv("OWLAB_DNS"); d != "" {
		return d
	}
	return "1.1.1.1 8.8.8.8"
}

func boolPtr(b bool) *bool { return &b }

// ServiceNames lists the compose services in a stable order.
func (p *Project) ServiceNames() []string {
	out := make([]string, 0, len(p.Config.Routers))
	for i := range p.Config.Routers {
		if p.Config.Routers[i].Fidelity != config.VM {
			out = append(out, p.Config.Routers[i].ID)
		}
	}
	sort.Strings(out)
	return out
}

// ContainerName is the container name for a router.
func (p *Project) ContainerName(id string) string {
	return p.Name + "-" + id
}
