// Package compose turns a parsed owlab.yaml into a Docker Compose file
// and the build context it refers to.
//
// Compose is an implementation detail: nothing outside this package should
// know the file exists. It is written into .owlab/ next to the project so
// that a developer debugging a strange container can read exactly what was
// asked for, but it is generated on every run and must never be edited.
package compose

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	owlab "github.com/VizzleTF/owlab"
	"github.com/VizzleTF/owlab/internal/config"
	"github.com/VizzleTF/owlab/internal/engine"
)

// WorkDirName is the per-project scratch directory owlab writes into.
const WorkDirName = ".owlab"

// File is the generated compose document.
type File struct {
	Name     string             `yaml:"name"`
	Services map[string]Service `yaml:"services"`
	Networks map[string]Network `yaml:"networks"`
}

// Service is one router.
type Service struct {
	Build           *Build            `yaml:"build,omitempty"`
	Image           string            `yaml:"image,omitempty"`
	Platform        string            `yaml:"platform,omitempty"`
	ContainerName   string            `yaml:"container_name"`
	Hostname        string            `yaml:"hostname"`
	CapAdd          []string          `yaml:"cap_add,omitempty"`
	Privileged      bool              `yaml:"privileged,omitempty"`
	Ports           []string          `yaml:"ports,omitempty"`
	ExtraHosts      []string          `yaml:"extra_hosts,omitempty"`
	Environment     map[string]string `yaml:"environment,omitempty"`
	Volumes         []string          `yaml:"volumes,omitempty"`
	Restart         string            `yaml:"restart,omitempty"`
	StopGracePeriod string            `yaml:"stop_grace_period,omitempty"`
	TTY             bool              `yaml:"tty,omitempty"`
	Init            *bool             `yaml:"init,omitempty"`
	Labels          map[string]string `yaml:"labels,omitempty"`
}

// Build is the build stanza for one router.
//
// There is deliberately no platform here. The compose spec has build.platforms
// (a list, for multi-platform builds) and rejects a scalar build.platform; the
// service-level platform below already selects what to build and what to run,
// which is what a single-arch dev router wants.
type Build struct {
	Context    string            `yaml:"context"`
	Dockerfile string            `yaml:"dockerfile"`
	Args       map[string]string `yaml:"args,omitempty"`
}

// Network is the single user-defined bridge every router joins.
type Network struct {
	Name   string `yaml:"name"`
	Driver string `yaml:"driver"`
}

// Project is where the generated files landed.
type Project struct {
	// ComposePath is the generated compose document.
	ComposePath string
	// ContextDir is the build context every service's build stanza points at.
	// Written by Materialize; the directory exists after Render, but is empty
	// until then.
	ContextDir string
}

// Render writes the compose file and returns where it landed.
//
// Deliberately cheap: it touches only the project's own .owlab directory and
// never opens a socket. Stopping a router or reading its log needs the compose
// file and nothing else, and paying for a build context — a wipe-and-rewrite
// of a directory plus however many downloads — to run `owlab down` would be
// both slow and, with no network, a reason for it to fail outright.
func Render(cfg *config.Config, eng engine.Info) (*Project, error) {
	work := filepath.Join(cfg.Dir, WorkDirName)
	ctxDir := filepath.Join(work, "context")
	if err := os.MkdirAll(ctxDir, 0o755); err != nil {
		return nil, err
	}
	if err := writeGitignore(work); err != nil {
		return nil, err
	}

	keyFile, err := writeAuthorizedKeys(work)
	if err != nil {
		return nil, err
	}

	name := ProjectName(cfg.Project.Name)
	doc := File{
		Name:     name,
		Services: map[string]Service{},
		Networks: map[string]Network{
			"default": {Name: name, Driver: "bridge"},
		},
	}
	for i := range cfg.Routers {
		r := &cfg.Routers[i]
		if r.Fidelity == config.VM {
			// The VM tier does not run under compose at all — it spawns QEMU
			// natively on the host, because Docker Desktop grants containers
			// no /dev/kvm on macOS or Windows 10.
			continue
		}
		doc.Services[r.ID] = service(cfg, r, eng, name, ctxDir, keyFile)
	}

	out, err := yaml.Marshal(doc)
	if err != nil {
		return nil, err
	}
	header := "# Generated by owlab from " + config.FileName + ". Do not edit — it is rewritten on every run.\n"
	composePath := filepath.Join(work, "compose.yaml")
	if err := os.WriteFile(composePath, append([]byte(header), out...), 0o644); err != nil {
		return nil, err
	}

	return &Project{ComposePath: composePath, ContextDir: ctxDir}, nil
}

// Materialize fills in the build context the compose file points at.
//
// This is the expensive half — the embedded context is wiped and rewritten,
// and the out-of-feed packages and compliance bundle are downloaded — so it is
// called only by the commands that are about to build an image.
func Materialize(cfg *config.Config, p *Project) error {
	if err := extractContext(p.ContextDir); err != nil {
		return fmt.Errorf("writing build context: %w", err)
	}
	// Both after extractContext, which wipes the directory first.
	cacheDir := filepath.Join(cfg.Dir, WorkDirName, "cache")
	if err := fetchExtraPackages(cfg, p.ContextDir, cacheDir); err != nil {
		return err
	}
	return fetchCompliance(cfg, p.ContextDir, cacheDir)
}

// Prepare renders the compose file and materialises the context it refers to,
// for the commands that are about to build.
func Prepare(cfg *config.Config, eng engine.Info) (*Project, error) {
	p, err := Render(cfg, eng)
	if err != nil {
		return nil, err
	}
	if err := Materialize(cfg, p); err != nil {
		return nil, err
	}
	return p, nil
}

// BuildArgsFor is every ARG the Dockerfile needs for one router.
//
// Exported because CI builds the published images with `docker buildx build`
// rather than through compose. Sharing this function is what keeps a
// published image identical to the one a developer builds locally.
func BuildArgsFor(cfg *config.Config, r *config.Router) map[string]string {
	args := map[string]string{
		"PKG_MANAGER":   string(r.PackageManager()),
		"PACKAGES":      strings.Join(r.Packages, " "),
		"FIXTURES":      strings.Join(r.Fixtures, " "),
		"ROUTER_ID":     r.ID,
		"THEME":         cfg.Project.Theme,
		"ROOT_PASSWORD": RootPassword(),
	}
	if base := r.BaseImage(); base != "" {
		args["BASE_STAGE"] = "upstream"
		args["BASE_IMAGE"] = base
	} else {
		args["BASE_STAGE"] = "tarball"
		args["ROOTFS_URL"] = r.RootfsTarballURL()
		// BASE_IMAGE still has to name something that resolves. buildkit reads
		// the metadata for every FROM in the file before it works out which
		// stages the target depends on, so leaving the default here makes a
		// tarball build fail on an image it is not going to use:
		//
		//   failed to resolve source metadata for
		//   docker.io/openwrt/rootfs:aarch64_generic-25.12.5: not found
		//
		// scratch resolves to nothing and costs nothing.
		args["BASE_IMAGE"] = "scratch"
	}
	return args
}

func service(cfg *config.Config, r *config.Router, eng engine.Info, project, ctxDir, keyFile string) Service {
	args := BuildArgsFor(cfg, r)

	svc := Service{
		Build: &Build{
			Context:    ctxDir,
			Dockerfile: "Dockerfile",
			Args:       args,
		},
		Image:         fmt.Sprintf("%s-%s:latest", project, r.ID),
		Platform:      r.Platform(),
		ContainerName: ContainerName(cfg.Project.Name, r.ID),
		Hostname:      r.Hostname,
		// NET_ADMIN and NET_RAW rather than privileged: netifd has to bring
		// interfaces up and add addresses, and fw4 has to load an nftables
		// ruleset, but neither needs the rest of what privileged grants.
		CapAdd: []string{"NET_ADMIN", "NET_RAW"},
		// Host ports are the ONLY portable way in. A bridge subnet is
		// routable from the host on native Linux and inside WSL2, but not on
		// Docker Desktop for Mac or Windows — so nothing in owlab may
		// address a router by its bridge IP.
		Ports: []string{
			fmt.Sprintf("%d:80", r.Ports.HTTP),
			fmt.Sprintf("%d:22", r.Ports.SSH),
		},
		// The way back out, and the reason it is a name rather than an address:
		// a router that installs from a feed served by the machine running owlab
		// has to address that machine, and no literal is right everywhere. The
		// default bridge gateway is 172.17.0.1 on a Linux runner, a user-defined
		// bridge has a different one, and Docker Desktop has none at all.
		// host-gateway is the daemon's own name for the answer, so the daemon
		// resolves it instead of us guessing. See pkgmgr.HostToken.
		ExtraHosts: []string{"host.docker.internal:host-gateway"},
		Environment: map[string]string{
			"OWLAB_DNS": dns(),
		},
		Restart:         "unless-stopped",
		StopGracePeriod: "5s",
		// procd writes its startup messages to /dev/console; without a tty
		// they go nowhere and `logs` is empty.
		TTY: true,
		// procd IS the init system here. Docker's own init would take PID 1
		// and everything that reads board data over ubus would come back
		// empty — which is what makes LuCI crash rather than degrade.
		Init: boolPtr(false),
		Labels: map[string]string{
			"org.owlab.project":  cfg.Project.Name,
			"org.owlab.router":   r.ID,
			"org.owlab.distro":   string(r.Distro),
			"org.owlab.release":  r.Release,
			"org.owlab.arch":     r.Arch,
			"org.owlab.fidelity": string(r.Fidelity),
		},
	}

	if keyFile != "" {
		// Staged at a read-only path and copied into place by the entrypoint,
		// because on native Linux a bind mount keeps the host's uid and
		// dropbear silently refuses an authorized_keys it does not see as
		// root's.
		svc.Volumes = append(svc.Volumes, keyFile+":/etc/owlab/authorized_keys.host:ro")
	}
	return svc
}

// extractContext writes the embedded build context to disk.
//
// Docker needs a real directory: BuildKit can take a context over stdin, but
// only as a tar stream, and that path loses the file modes the overlay
// depends on.
func extractContext(dir string) error {
	src := owlab.BuildContext()
	// Remove first, so a file dropped from a newer owlab does not linger in a
	// project directory that an older one wrote.
	if err := os.RemoveAll(dir); err != nil {
		return err
	}
	return fs.WalkDir(src, ".", func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		target := filepath.Join(dir, filepath.FromSlash(p))
		if d.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		b, err := fs.ReadFile(src, p)
		if err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		mode := fs.FileMode(0o644)
		if strings.HasSuffix(p, ".sh") || strings.Contains(p, "uci-defaults/") {
			mode = 0o755
		}
		return os.WriteFile(target, b, mode)
	})
}

func writeGitignore(work string) error {
	// Everything in here is generated. Writing the ignore file ourselves
	// keeps it out of the developer's repository without asking them to
	// remember a line in .gitignore.
	return os.WriteFile(filepath.Join(work, ".gitignore"), []byte("*\n"), 0o644)
}

// ProjectName is the compose project name, and the prefix of every container
// and network name.
func ProjectName(s string) string {
	s = strings.ToLower(s)
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == '-' || r == '_':
			b.WriteRune('-')
		}
	}
	out := strings.Trim(b.String(), "-")
	if out == "" {
		out = "project"
	}
	return "owlab-" + out
}

// ContainerName is the container one router runs in.
//
// projectName is the raw name from owlab.yaml, not an already-normalised one:
// ProjectName is not idempotent (it prefixes "owlab-"), so feeding it its own
// output would name a container nothing can find.
func ContainerName(projectName, routerID string) string {
	return ProjectName(projectName) + "-" + routerID
}

// PublicKeys lists the ssh public keys to install, and where they came from.
//
// ALL of the user's standard keys, not the first one found. Picking one by
// preference order means someone who has both an ed25519 and an rsa key, and
// reaches for the rsa one, is told "Permission denied (publickey)" by a box
// that holds a key they also own. Installing every key they have removes the
// question.
//
// Only `id_*.pub` is collected, not every .pub in the directory: ~/.ssh
// routinely holds other people's keys and ones downloaded for a specific
// host, and those are not the developer's identity to install here.
func PublicKeys() (paths []string, source string) {
	// An explicit setting replaces the search outright. It takes a file, or
	// several separated by the platform's path separator.
	if env := os.Getenv("OWLAB_PUBKEY"); env != "" {
		for _, p := range filepath.SplitList(env) {
			if st, err := os.Stat(p); err == nil && !st.IsDir() {
				paths = append(paths, p)
			}
		}
		return paths, "OWLAB_PUBKEY"
	}

	home, err := os.UserHomeDir()
	if err != nil {
		return nil, ""
	}
	matches, _ := filepath.Glob(filepath.Join(home, ".ssh", "id_*.pub"))
	sort.Strings(matches)
	for _, p := range matches {
		if st, err := os.Stat(p); err == nil && !st.IsDir() {
			paths = append(paths, p)
		}
	}
	return paths, filepath.Join(home, ".ssh")
}

// AuthorizedKeys is the contents of the authorized_keys file to install: every
// key PublicKeys found, one per line, unreadable and empty ones dropped.
//
// Exported because both tiers install the same keys by different means — the
// container mounts a file the entrypoint copies into place, the VM has the
// bytes pushed in with the rest of its overlay — and a developer whose ssh
// works on one router and not the other would have no way to tell why.
func AuthorizedKeys() []byte {
	paths, _ := PublicKeys()
	var b strings.Builder
	for _, p := range paths {
		body, err := os.ReadFile(p)
		if err != nil {
			continue
		}
		line := strings.TrimSpace(string(body))
		if line == "" {
			continue
		}
		b.WriteString(line)
		b.WriteString("\n")
	}
	return []byte(b.String())
}

// writeAuthorizedKeys stages the keys in the work directory for the container
// to pick up, and returns the path — or "" when there are none.
func writeAuthorizedKeys(workDir string) (string, error) {
	keys := AuthorizedKeys()
	if len(keys) == 0 {
		return "", nil
	}
	out := filepath.Join(workDir, "authorized_keys")
	if err := os.WriteFile(out, keys, 0o644); err != nil {
		return "", err
	}
	return out, nil
}

// RootPassword is the router's root password, empty unless one is asked for.
//
// Empty is what a stock OpenWrt rootfs ships with, and it is the right
// default for a throwaway box on localhost: LuCI still shows its login form
// but accepts an empty field, so there is nothing to remember. ssh key auth
// is unaffected.
func RootPassword() string { return os.Getenv("OWLAB_ROOT_PASSWORD") }

func dns() string {
	if d := os.Getenv("OWLAB_DNS"); d != "" {
		return d
	}
	return "1.1.1.1 8.8.8.8"
}

func boolPtr(b bool) *bool { return &b }
